### ISSUE TITLE
gi2ds bookmarklet might not work on some browsers

### ISSUE THREAD

**Issue by hweecat** [yoke2/tf2_data_to_app_workshop#1]
Tried using gi2ds bookmarklet (https://github.com/toffebjorkskog/ml-tools/blob/master/gi2ds.md) on the following browsers:

- Chrome: Works on my personal laptop, Security issues on my work laptop when using work network
- Microsoft Edge: Might not work sometimes - shows '0: undefined' when scrolling. Works on my personal laptop.
- Firefox: Works

**Comment by yoke2** [comment]
Thanks for testing! Added alternative method (via Chrome Extension) in slides.
